
name = "Your Name"
title = "Senior Android Engineer"
location = "Auckland, New Zealand"
email = "youremail@example.com"
phone = "+64-21-123-4567"
website = "https://yourwebsite.com"
summary = "Experienced Android developer with 10+ years of delivering robust mobile solutions."

[[experience]]
position = "Senior Android Developer"
company = "Company A"
duration = "2020 - Present"
description = "Leading Android projects using Kotlin, Compose, and modern architectures."

[[experience]]
position = "Android Engineer"
company = "Company B"
duration = "2016 - 2020"
description = "Developed apps with millions of downloads, focused on performance and UX."

[[projects]]
title = "Project Alpha"
description = "An AI-powered mobile app for health tracking."

[[projects]]
title = "Project Beta"
description = "Secure messaging app with E2EE, built on Android SDK."

[[certifications]]
name = "Google Associate Android Developer"
year = "2023"

[[certifications]]
name = "AWS Certified Developer – Associate"
year = "2022"

tags = ["Android", "Kotlin", "Jetpack Compose", "MVVM", "Coroutines", "New Zealand", "Agile"]
